name: 'Review Reminder'
description: 'Notify in chat about build results.'
author: 'Logan Ramos'
inputs:
  token:
    description: GitHub token.
    default: ${{ github.token }}
    required: true
  slack_token:
    description: Slack token.
    required: true
runs:
  using: 'node20'
  main: 'index.js'
